site_name: Glasgow Project

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo1.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.mark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  
  - Coursework:
    - AI Law:
      - Reading List: AI Law/01 Reading List.md
      - PPT: AI Law/02 PPT.md
    - Copyright Law:
      - Reading List: Copyright Law/01 Reading List.md
      - PPT: Copyright Law/02 PPT.md
    - Academic Writting:
      - OSCOLA 4th Edition: Academic Writting/OSCOLA 4th Edition.md
      - APA 7th Edition: Academic Writting/APA 7th Edition.md
      - Useful: Academic Writting/Useful.md
  
  - DDL-Related Materials: DDL/DDL.md