site_name: Glasgow Project

theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/logo1.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # 浅色
    - scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    # 深色
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

markdown_extensions:
  - pymdownx.mark

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  
  - Courses:
    - Academic Writting:
      - 1. OSCOLA 4th Edition: Academic Writting/OSCOLA 4th Edition.md
      - 2. APA 7th Edition: Academic Writting/APA 7th Edition.md
      - 3. Useful: Academic Writting/Useful.md
    - AI Law:
      - 1. Course Information: AI Law/01 Course Information.md
      - 2. PPT & Reading List: AI Law/02 PPT & Reading List.md
    - Contemporary IP:
      - 2. PPT & Reading List: Contemporary IP/02 PPT & Reading List.md
    - Copyright Law:
      - 1. Course Information: Copyright Law/01 Course Information.md
      - 2. PPT & Reading List: Copyright Law/02 PPT & Reading List.md
      - 3. Definitions: Copyright Law/03 Definitions.md
  
  - DDL-Related Materials: DDL/DDL.md