site_name: Glasgow Project

theme: 
  name: material
  features:
    - navigation.tabs

nav:
  - Home: index.md

  - AI Law:
    - Reading List: AI Law/01 Reading List.md
    - PPT: AI Law/02 PPT.md
  
  - Copyright Law:
    - Reading List: Copyright Law/01 Reading List.md
    - PPT: Copyright Law/02 PPT.md
  
  - Academic Writting:
    - OSCOLA 4th Edition: Academic Writting/OSCOLA 4th Edition.md
    - APA 7th Edition: Academic Writting/APA 7th Edition.md
    - Useful: Academic Writting/Useful.md